/* Extracted unchanged from gold master 0.27.5. */
export const RESEARCH_PROJECTS={
  core_fitting:{id:'core_fitting',cat:'combat',name:'Core Fitting Principles',cost:0,prereq:[],desc:'Baseline powergrid, capacitor, mass, hardpoint and internal-system relationships.',unlocks:'BASE FITTING + CAPACITOR ANALYSIS'},
  starter_fabrication:{id:'starter_fabrication',cat:'fleet',name:'Starter Fabrication',cost:0,prereq:['core_fitting'],desc:'Foundational hull-printing methods used throughout Asterion starter construction.',unlocks:'STARTER HULL FABRICATION'},
  destroyer_architecture:{id:'destroyer_architecture',cat:'fleet',name:'Destroyer Architecture',cost:42,prereq:['starter_fabrication'],desc:'Reinforced keel, expanded bank routing and reactor geometry for the first true warship tier.',unlocks:'DESTROYER BLUEPRINT FAMILY'},
  frigate_specialization:{id:'frigate_specialization',cat:'fleet',name:'Frigate Specialisation',cost:48,prereq:['starter_fabrication'],desc:'High-output compact frames for assault, electronic, exploration and specialist roles.',unlocks:'ASSAULT + SPECIALITY FRIGATES // FUTURE ROSTER'},
  capacitor_dynamics:{id:'capacitor_dynamics',cat:'combat',name:'Nonlinear Capacitor Dynamics',cost:50,prereq:['core_fitting'],desc:'Peak recharge, reserve-bank architecture and efficient sustained-fire reactor plumbing.',unlocks:'CAP BATTERY // FLUX RECHARGER // STABLE FIRE-CONTROL // EFFICIENT DRIVE'},
  active_tanking:{id:'active_tanking',cat:'combat',name:'Active Tank Engineering',cost:64,prereq:['capacitor_dynamics'],desc:'Closed-loop shield injection and armour reconstruction trading capacitor for survivability.',unlocks:'AEGIS BOOSTER CROWN // ARMOUR NANOFORGE'},
  drone_command:{id:'drone_command',cat:'ai',name:'Autonomous Drone Command',cost:58,prereq:['core_fitting'],desc:'Distributed command mesh for combat, sentry, salvage and industrial autonomous wings.',unlocks:'INTERCEPTOR // SENTRY // SALVAGE // MINING DRONES'},
  ai_cognition:{id:'ai_cognition',cat:'ai',name:'Bounded AI Cognition',cost:86,prereq:['capacitor_dynamics'],desc:'Trainable inference lattices and constraint geometry for hull-integrated sovereign intelligence.',unlocks:'COVENANT + ORACLE AI CORES // AI LATTICE TRAINING'},
  wild_cognition:{id:'wild_cognition',cat:'ai',name:'Wild Cognition',cost:132,prereq:['ai_cognition'],desc:'Intentionally under-constrained cognition able to rewrite combat priorities around the hull.',unlocks:'WILD + ANOMALY AI CORE BLUEPRINTS'},
  cruiser_architecture:{id:'cruiser_architecture',cat:'fleet',name:'Cruiser Continuum',cost:78,prereq:['destroyer_architecture'],desc:'Sustained warship architecture bridging destroyer kinetics and capital endurance.',unlocks:'CRUISER + HEAVY CRUISER FAMILY // FUTURE ROSTER'},
  battlecruiser_theory:{id:'battlecruiser_theory',cat:'fleet',name:'Battlecruiser Theory',cost:92,prereq:['cruiser_architecture'],desc:'Oversized weapon architecture carried by cruiser-derived propulsion and command frames.',unlocks:'ADVANCED CRUISER + BATTLECRUISER FAMILY // FUTURE ROSTER'},
  battleship_architecture:{id:'battleship_architecture',cat:'fleet',name:'Battleship Architecture',cost:118,prereq:['destroyer_architecture'],desc:'Deep armour zoning, multi-bank trunks and strategic reactor redundancy.',unlocks:'ELITE BATTLESHIP BLUEPRINT FAMILY'},
  capital_ordnance:{id:'capital_ordnance',cat:'combat',name:'Capital Ordnance',cost:92,prereq:['battleship_architecture'],desc:'Siege-grade emitters and void ordnance designed for capital armour penetration.',unlocks:'SIEGE BEAM // VOID TORPEDO'},
  black_current_materials:{id:'black_current_materials',cat:'industry',name:'Black Current Materials',cost:74,prereq:['capacitor_dynamics'],desc:'Controlled processing of anomalous crystalline, void and living substrates.',unlocks:'VOID GLASS + ADVANCED MATERIAL RECIPES'},
  sovereign_industry:{id:'sovereign_industry',cat:'industry',name:'Sovereign Shipyard Methods',cost:72,prereq:['destroyer_architecture'],desc:'Persistent multi-job shipyard scheduling, blueprint lineage and modular hull fabrication.',unlocks:'ADVANCED HULL MANUFACTURING METHODS'},
  zj_cartography:{id:'zj_cartography',cat:'navigation',name:'Micro ZJ Cartography',cost:96,prereq:['black_current_materials'],desc:'Navigation solutions for stable transit through local Black Current discontinuities.',unlocks:'EXPANDED ZJ NETWORK // FUTURE 18+ DESTINATIONS'},
  station_architecture:{id:'station_architecture',cat:'industry',name:'Station Architecture',cost:120,prereq:['sovereign_industry','black_current_materials'],desc:'Civilisation-scale dock, refinery, research and fleet-service architecture.',unlocks:'REGIONAL STATIONS + SHIPYARDS // FUTURE NETWORK'},
  subcapital_architecture:{id:'subcapital_architecture',cat:'fleet',name:'Sub-Capital Warforms',cost:158,prereq:['battleship_architecture','capital_ordnance'],desc:'Dreads, Bailisks, Maraurads, Vamyreses, Sentinels and carrier-scale warforms.',unlocks:'SUB-CAPITAL FAMILIES // FUTURE ROSTER'},
  capital_architecture:{id:'capital_architecture',cat:'fleet',name:'Capital Civilisation Hulls',cost:210,prereq:['subcapital_architecture','station_architecture'],desc:'Fleet carriers, industrial capitals and autonomous fleet cores as strategic infrastructure.',unlocks:'CAPITAL WARSHIPS + CARRIERS + FLEET CORES'},
  titan_theory:{id:'titan_theory',cat:'fleet',name:'Titan Theory',cost:320,prereq:['capital_architecture','wild_cognition'],desc:'Apex theory where a ship becomes a mobile civilisation object.',unlocks:'TITANS // SUPER CARRIERS // EXPERIMENTAL ANOMALIES'}
};
