/* Extracted unchanged from gold master 0.27.5. */
export const MODULE_CATALOG={
  earned_battery:{id:'earned_battery',slot:'weapon',name:'Earned-Light Battery',cost:0,pg:46,mass:22,visual:'weapon',desc:'Heavy capital emitters tuned for decisive impact.',effect:'+22% turret damage · -8% turret cadence',stats:{turretDamage:1.22,turretRate:.92,weaponCapUse:1.08}},
  cheetah_repeater:{id:'cheetah_repeater',slot:'weapon',name:'Cheetah Repeater Matrix',cost:240,pg:35,mass:15,visual:'weapon',desc:'Fast cycling emitter lattice for swarm suppression.',effect:'+32% turret cadence · -12% turret damage',stats:{turretDamage:.88,turretRate:1.32,weaponCapUse:.88}},
  aegis_projector:{id:'aegis_projector',slot:'defense',name:'Aegis Projector',cost:0,pg:62,mass:34,visual:'shield',desc:'Expands shield capacity while retaining localized impact rendering.',effect:'+30% shield · +20% shield regeneration',stats:{shield:1.30,shieldRegen:1.20}},
  sovereign_plating:{id:'sovereign_plating',slot:'defense',name:'Sovereign Plating',cost:260,pg:28,mass:76,visual:'armor',desc:'Dense layered armour around reactor and keel corridors.',effect:'+25% armour · +15% hull',stats:{armor:1.25,hull:1.15}},
  earned_drive:{id:'earned_drive',slot:'drive',name:'Earned-Light Drive',cost:0,pg:56,mass:31,visual:'drive',desc:'Overcharged capital thrust architecture for long vector burns.',effect:'+30% top speed · +15% thrust',stats:{maxSpeed:1.30,accel:1.15,boostCapUse:.82}},
  vector_thrusters:{id:'vector_thrusters',slot:'drive',name:'Vector Thruster Crown',cost:220,pg:42,mass:20,visual:'drive',desc:'Distributed control vanes improve rotation of the enormous frame.',effect:'+38% turning · +5% top speed',stats:{turn:1.38,maxSpeed:1.05,boostCapUse:.92}},
  pd_mesh:{id:'pd_mesh',slot:'utility',name:'Point Defence Mesh',cost:0,pg:30,mass:12,visual:'utility',desc:'Predictive fire-control mesh synchronises autonomous hardpoints.',effect:'+22% turret cadence · +5% turret damage · -22% weapon capacitor',stats:{turretRate:1.22,turretDamage:1.05,weaponCapUse:.78,capRegen:1.08}},
  reactor_channel:{id:'reactor_channel',slot:'utility',name:'Black-Sun Reactor Channel',cost:310,pg:48,mass:18,visual:'reactor',desc:'Redirects singularity output toward active sovereign systems.',effect:'+28% ability damage · +28% capacitor · +35% recharge',stats:{abilityDamage:1.28,shield:1.08,capacitor:1.28,capRegen:1.35,abilityCapUse:.88}},
  void_lance:{id:'void_lance',slot:'weapon',name:'Void-Lance Battery',cost:480,pg:72,mass:31,visual:'weapon',sectorReq:'erebos',desc:'Erebos-forged emitters compress fire into slower, catastrophic penetrator cycles.',effect:'+44% turret damage · -24% turret cadence',stats:{turretDamage:1.44,turretRate:.76}},
  phase_aegis:{id:'phase_aegis',slot:'defense',name:'Phase Aegis',cost:520,pg:78,mass:38,visual:'shield',sectorReq:'erebos',desc:'A phase-offset shield architecture recovered from the Mirror Well.',effect:'+48% shield · -8% regen · +10% hull',stats:{shield:1.48,shieldRegen:.92,hull:1.10}},
  gravitic_drive:{id:'gravitic_drive',slot:'drive',name:'Gravitic Crown Drive',cost:500,pg:84,mass:28,visual:'drive',sectorReq:'erebos',desc:'Curves local vector space around the capital frame for impossible sustained translation.',effect:'+43% top speed · +18% thrust · -10% turning',stats:{maxSpeed:1.43,accel:1.18,turn:.90,boostCapUse:1.16,capacitor:1.08}},
  oracle_mesh:{id:'oracle_mesh',slot:'utility',name:'Oracle War-Mesh',cost:560,pg:58,mass:16,visual:'utility',sectorReq:'erebos',desc:'Predictive Erebos targeting logic channels reactor output into weapons and sovereign abilities.',effect:'+38% ability output · +18% capacitor recharge · -20% ability capacitor',stats:{abilityDamage:1.38,turretRate:1.12,capRegen:1.18,abilityCapUse:.80,weaponCapUse:.92}},
  targeting_core:{id:'targeting_core',slot:'weapon',name:'Targeting Harmonic Core',cost:150,pg:32,mass:11,visual:'weapon',desc:'Generalized fire-control upgrade for mixed weapon doctrines.',effect:'+12% turret damage · +12% cadence · -8% weapon capacitor',stats:{turretDamage:1.12,turretRate:1.12,weaponCapUse:.92}},
  siege_calibrator:{id:'siege_calibrator',slot:'weapon',name:'Siege Calibrator',cost:310,pg:51,mass:24,visual:'weapon',desc:'Heavy fire-control architecture for deliberate capital volleys.',effect:'+30% turret damage · -12% cadence',stats:{turretDamage:1.30,turretRate:.88,weaponCapUse:1.10}},
  reactive_armor:{id:'reactive_armor',slot:'defense',name:'Reactive Armour Web',cost:180,pg:24,mass:54,visual:'armor',desc:'Layered sacrificial armour with a modest hull reinforcement.',effect:'+18% armour · +8% hull',stats:{armor:1.18,hull:1.08}},
  prism_barrier:{id:'prism_barrier',slot:'defense',name:'Prism Barrier',cost:235,pg:52,mass:24,visual:'shield',desc:'Light shield architecture emphasizing regeneration over raw capacity.',effect:'+14% shield · +38% shield regeneration',stats:{shield:1.14,shieldRegen:1.38}},
  flux_drive:{id:'flux_drive',slot:'drive',name:'Flux Racing Drive',cost:195,pg:48,mass:18,visual:'drive',desc:'Lightweight drive for frigates and aggressive cruiser fits.',effect:'+24% speed · +28% acceleration · +10% turn',stats:{maxSpeed:1.24,accel:1.28,turn:1.10,boostCapUse:1.08}},
  bastion_drive:{id:'bastion_drive',slot:'drive',name:'Bastion Vector Drive',cost:275,pg:38,mass:44,visual:'drive',desc:'Heavy stabilization package for large artillery hulls.',effect:'+18% turn · -8% speed · -18% boost capacitor',stats:{turn:1.18,maxSpeed:.92,boostCapUse:.82}},
  cap_matrix:{id:'cap_matrix',slot:'utility',name:'Capacitor Matrix',cost:175,pg:34,mass:10,visual:'reactor',desc:'Straightforward reactor buffer and recharge augmentation.',effect:'+18% capacitor · +22% recharge',stats:{capacitor:1.18,capRegen:1.22}},
  damage_control:{id:'damage_control',slot:'utility',name:'Damage Control Lattice',cost:225,pg:28,mass:16,visual:'utility',desc:'Distributed reinforcement and emergency-repair routing for damaged sovereign hulls.',effect:'+8% shield · +10% armour · +10% structure · +45% damage-control repair · -28% repair capacitor',stats:{shield:1.08,armor:1.10,hull:1.10,damageControlRate:1.45,damageControlCapUse:.72}},
  war_reactor:{id:'war_reactor',slot:'utility',name:'War Reactor',cost:330,pg:44,mass:17,visual:'reactor',desc:'Aggressive reactor tune for weapon-heavy fleets.',effect:'+18% capacitor · +12% recharge · -14% weapon capacitor',stats:{capacitor:1.18,capRegen:1.12,weaponCapUse:.86}}
};

Object.assign(MODULE_CATALOG,{
  ai_core_covenant:{id:'ai_core_covenant',slot:'defense',name:'Covenant AI Core',cost:290,pg:46,mass:14,visual:'ai_core',aiCore:true,aiTier:1,desc:'Bounded adaptive intelligence. Resolves a hull-specific benefit and a smaller cost when paired.',effect:'UNKNOWN UNTIL PAIRED // LOW STRAIN'},
  ai_core_oracle:{id:'ai_core_oracle',slot:'defense',name:'Oracle AI Core',cost:440,pg:61,mass:16,visual:'ai_core',aiCore:true,aiTier:2,desc:'Predictive sovereign intelligence permitted to rewrite targeting, propulsion or tank priorities.',effect:'UNKNOWN UNTIL PAIRED // MODERATE STRAIN'},
  ai_core_wild:{id:'ai_core_wild',slot:'defense',name:'Wild AI Core',cost:610,pg:78,mass:18,visual:'ai_core',aiCore:true,aiTier:3,desc:'Intentionally under-constrained intelligence. Strong adaptive mutation with a serious hull-specific cost.',effect:'UNKNOWN UNTIL PAIRED // HIGH STRAIN'},
  ai_core_anomaly:{id:'ai_core_anomaly',slot:'defense',name:'Anomaly AI Core',cost:900,pg:104,mass:23,visual:'ai_core',aiCore:true,aiTier:4,desc:'Extreme architecture. The intelligence may restructure the fit around its own inferred combat objective.',effect:'UNKNOWN UNTIL PAIRED // EXTREME STRAIN'}
});


Object.assign(MODULE_CATALOG,{
  stable_fire_control:{id:'stable_fire_control',slot:'weapon',name:'Stable Fire-Control Bus',cost:165,pg:27,mass:10,visual:'weapon',desc:'Conservative fire-control for capacitor-stable sustained batteries.',effect:'-30% weapon capacitor · +5% cadence · -5% turret damage',stats:{turretDamage:.95,turretRate:1.05,weaponCapUse:.70}},
  capacitor_battery_bank:{id:'capacitor_battery_bank',slot:'utility',name:'Deep Capacitor Battery',cost:230,pg:31,mass:18,visual:'reactor',desc:'Large reserve cells increase endurance but slow natural recharge.',effect:'+38% capacitor · -10% recharge',stats:{capacitor:1.38,capRegen:.90}},
  flux_recharger:{id:'flux_recharger',slot:'utility',name:'Flux Recharger',cost:245,pg:39,mass:12,visual:'reactor',desc:'High-throughput reactor plumbing trades reserve depth for aggressive peak recharge.',effect:'+42% recharge · -10% capacitor',stats:{capacitor:.90,capRegen:1.42}},
  efficient_vector_drive:{id:'efficient_vector_drive',slot:'drive',name:'Efficient Vector Drive',cost:210,pg:37,mass:19,visual:'drive',desc:'Lower-draw propulsion crown for ships that must retain capacitor while manoeuvring.',effect:'+12% speed · +8% acceleration · -28% boost capacitor',stats:{maxSpeed:1.12,accel:1.08,boostCapUse:.72}},
  armor_nanoforge:{id:'armor_nanoforge',slot:'defense',name:'Armour Nanoforge',cost:285,pg:36,mass:43,visual:'armor',desc:'Active armour restoration architecture. Lower buffer, real combat repair.',effect:'+12% armour · AUTO ACTIVE REPAIR // capacitor driven',stats:{armor:1.12}},
  active_aegis_booster:{id:'active_aegis_booster',slot:'defense',name:'Aegis Booster Crown',cost:295,pg:68,mass:29,visual:'shield',desc:'Heavy active shield booster for burst tanking. Excellent recovery, significant capacitor demand.',effect:'+12% shield · AUTO ACTIVE BOOST // capacitor driven',stats:{shield:1.12,shieldRegen:1.08}}
});

export const MODULE_RUNTIME={
  aegis_projector:{mode:'active',kind:'shield_boost',cycle:3.2,cap:24,amount:112,threshold:.74,label:'AUTO SHIELD BOOST'},
  prism_barrier:{mode:'active',kind:'shield_boost',cycle:2.25,cap:17,amount:66,threshold:.88,label:'FAST SHIELD BOOST'},
  phase_aegis:{mode:'active',kind:'shield_boost',cycle:4.0,cap:34,amount:158,threshold:.68,label:'HEAVY PHASE BOOST'},
  active_aegis_booster:{mode:'active',kind:'shield_boost',cycle:2.8,cap:31,amount:148,threshold:.80,label:'BURST SHIELD BOOST'},
  reactive_armor:{mode:'active',kind:'armor_repair',cycle:4.15,cap:27,amount:82,threshold:.82,label:'AUTO ARMOUR REPAIR'},
  armor_nanoforge:{mode:'active',kind:'armor_repair',cycle:3.45,cap:33,amount:122,threshold:.86,label:'NANOFORGE REPAIR'}
};
