/* Extracted unchanged from gold master 0.27.5. */
export const TURRET_CATALOG={
  autocannon:{id:'autocannon',name:'Earned-Light Autocannon',cost:0,tier:1,size:'LIGHT',pg:24,mass:11,cap:5,optimal:135,falloff:70,tracking:0.72,damageType:'kinetic',desc:'Balanced kinetic capital battery. Strong inside optimal range with forgiving falloff.',damage:1,rate:1,speed:235,range:190,radius:.16,color:0x65f5ff,barrelLength:1,barrelWidth:1,material:'armor'},
  repeater:{id:'repeater',name:'Cheetah Repeater',cost:130,tier:1,size:'LIGHT',pg:18,mass:8,cap:3,optimal:82,falloff:68,tracking:1.5,damageType:'kinetic',desc:'High-tracking kinetic repeater built to shred fast frigates inside close optimal range.',damage:.62,rate:1.85,speed:285,range:150,radius:.13,color:0x69fbff,barrelLength:.75,barrelWidth:.82,material:'cyan'},
  railgun:{id:'railgun',name:'Sovereign Railgun',cost:190,tier:3,size:'HEAVY',pg:47,mass:24,cap:15,optimal:235,falloff:65,tracking:0.22,damageType:'kinetic',desc:'Long-optimal kinetic penetrator. Devastating against armour, poor tracking on fast targets.',damage:2.35,rate:.43,speed:390,range:285,radius:.20,color:0xffcf6b,barrelLength:1.55,barrelWidth:.88,material:'gold'},
  plasma:{id:'plasma',name:'Black-Sun Plasma Cannon',cost:235,tier:2,size:'MEDIUM',pg:38,mass:19,cap:11,optimal:120,falloff:70,tracking:0.48,damageType:'thermal',desc:'Thermal plasma projector. Strong against shields, useful armour pressure, moderate tracking.',damage:1.58,rate:.72,speed:185,range:180,radius:.27,color:0xb966ff,barrelLength:1.18,barrelWidth:1.34,material:'purple'},
  void_torpedo:{id:'void_torpedo',name:'Void Torpedo Rack',cost:430,tier:4,size:'CAPITAL',pg:58,mass:29,cap:18,optimal:245,falloff:80,tracking:0.16,damageType:'void',sectorReq:'erebos',desc:'Guided void ordnance with capital reach. Punishes hull and subsystems but tracks small targets poorly.',damage:3.15,rate:.27,speed:128,range:310,radius:.34,color:0xcd6cff,homing:true,barrelLength:.72,barrelWidth:1.55,material:'purple'},
  flak:{id:'flak',name:'Storm Flak Array',cost:95,tier:1,size:'LIGHT',pg:16,mass:7,cap:2,optimal:62,falloff:55,tracking:1.85,damageType:'explosive',desc:'Ultra-high tracking defensive cannon for fighters and starter hulls.',damage:.48,rate:2.20,speed:310,range:115,radius:.12,color:0xff755e,barrelLength:.62,barrelWidth:.88,material:'armor'},
  beam_laser:{id:'beam_laser',name:'Aurelian Beam Lance',cost:155,tier:1,size:'LIGHT',pg:30,mass:12,cap:10,optimal:175,falloff:48,tracking:.76,damageType:'thermal',desc:'Fast thermal projection with excellent shield pressure and clean precision.',damage:1.05,rate:1.05,speed:520,range:230,radius:.13,color:0xffd989,barrelLength:1.20,barrelWidth:.70,material:'gold'},
  missile:{id:'missile',name:'Nomad Missile Rack',cost:175,tier:2,size:'MEDIUM',pg:28,mass:13,cap:5,optimal:160,falloff:75,tracking:.58,damageType:'explosive',desc:'Guided explosive ordnance with forgiving range and strong hull damage.',damage:1.22,rate:.78,speed:175,range:245,radius:.20,color:0xff657b,homing:true,barrelLength:.72,barrelWidth:1.32,material:'armor'},
  ion:{id:'ion',name:'Prism Ion Projector',cost:210,tier:2,size:'MEDIUM',pg:35,mass:14,cap:13,optimal:145,falloff:62,tracking:.88,damageType:'thermal',desc:'High-tracking ion fire tuned for shield stripping and subsystem pressure.',damage:1.14,rate:.92,speed:330,range:220,radius:.18,color:0x82edff,barrelLength:1.05,barrelWidth:.82,material:'cyan'},
  shard:{id:'shard',name:'Ossuary Shard Cannon',cost:205,tier:2,size:'MEDIUM',pg:34,mass:18,cap:6,optimal:105,falloff:85,tracking:.64,damageType:'kinetic',desc:'Brutal close kinetic cannon with broad falloff and armour-breaking volleys.',damage:1.48,rate:.74,speed:250,range:210,radius:.24,color:0xffb264,barrelLength:1.05,barrelWidth:1.25,material:'armor'},
  siege_beam:{id:'siege_beam',name:'Seraphim Siege Beam',cost:365,tier:4,size:'CAPITAL',pg:52,mass:24,cap:20,optimal:270,falloff:55,tracking:.24,damageType:'thermal',desc:'Capital thermal artillery for battleships, dreadnoughts and Titans.',damage:2.55,rate:.38,speed:620,range:335,radius:.21,color:0xffe0a3,barrelLength:1.70,barrelWidth:.78,material:'gold'}
};
